# Generated by Django 4.2.6 on 2024-05-02 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_book_medicine_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='medicine_name',
            new_name='medicine_r',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='medicine_name',
            new_name='medicine_r',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='medicine',
        ),
    ]
