# Generated by Django 4.2.6 on 2024-05-02 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_rename_medicine_name_book_medicine_r_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='medicine_r',
            new_name='medicine',
        ),
    ]
