# Generated by Django 5.0.3 on 2024-05-02 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_rename_medicine_r_medicine_medicine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='date',
        ),
        migrations.RemoveField(
            model_name='book',
            name='quantity',
        ),
        migrations.AddField(
            model_name='book',
            name='quantity_r',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicine',
            name='quantity',
            field=models.DecimalField(decimal_places=0, max_digits=3),
        ),
    ]
