# Generated by Django 5.0.3 on 2024-05-02 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_remove_book_date_remove_book_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=100)),
                ('appointment_mood', models.CharField(max_length=100)),
                ('appointment_time', models.DateTimeField()),
                ('appointment_length', models.IntegerField()),
            ],
        ),
    ]
